#!/bin/bash


#PBS -N corset-cluster-STVokay

#PBS -A UQ-SCI-SCMB

#PBS -l nodes=1:ppn=24:intel,mem=500GB,walltime=330:00:00

#PBS -m ea

#PBS -M kwathen-dunn@sugarresearch.com.au


module load samtools


/home/s4439186/ycs/my-software/corset-1.06-linux64/corset -D 99999999999 -p STV.okay -g 1,1,1,2,2,2 -n Control-soapTrans.okay,Control-trinity.okay,Control-velvet.okay,YCS-soapTrans.okay,YCS-trinity.okay,YCS-velvet.okay /30days/s4439186/*.bam
